In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import shutil
import scipy as sc

In [5]:
ds_total = np.array(np.zeros((63*5,7)))
pd.DataFrame(ds_total)

       0    1    2    3    4    5    6
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0
..   ...  ...  ...  ...  ...  ...  ...
310  0.0  0.0  0.0  0.0  0.0  0.0  0.0
311  0.0  0.0  0.0  0.0  0.0  0.0  0.0
312  0.0  0.0  0.0  0.0  0.0  0.0  0.0
313  0.0  0.0  0.0  0.0  0.0  0.0  0.0
314  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[315 rows x 7 columns]

In [6]:
from os import listdir


path = "C:\Repositorios\Simulacao_MIT\Classificador\MLP\dataset\csv_files\join_all_ds"
os.chdir(path)
for file in os.listdir():
    os.chdir(path)
    ds = pd.read_csv(file)
    pd.DataFrame(ds)
    pd.concat([ds_total, ds], ignore_index=True)

TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid